import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {signedFrames,coherentSweep,standings,indexPublished,signedTrade,predictEntries} from '../scripts/trading.mjs';import {verified} from '../scripts/rank.mjs';
const source=JSON.parse(fs.readFileSync('config/source.json'));const seed=JSON.parse(fs.readFileSync('config/seed.json'));const evidence=JSON.parse(fs.readFileSync('public/api/evidence.json'));
test('pinned real seed verifies and matches the rules commitment',()=>{assert.ok(verified('d-close1-price',seed));assert.equal(seed.from,source.refereeDid);assert.equal(JSON.parse(seed.text).package,source.manifestSha256)});
test('real referee feeds verify; wrong signer and tampered messages fail',()=>{for(const {room,message} of Object.values(evidence.feeds)){assert.equal(signedFrames(room,{messages:[message]},source.refereeDid).length,1);assert.equal(signedFrames(room,{messages:[{...message,text:message.text+'x'}]},source.refereeDid).length,0);assert.equal(signedFrames(room,{messages:[message]},'other').length,0)}});
test('select latest common sweep, reject missing feeds and inconsistent commitments',()=>{const feeds=Object.fromEntries(Object.entries(evidence.feeds).map(([type,{room,message}])=>[type,signedFrames(room,{messages:[message]},source.refereeDid)]));const result=coherentSweep(feeds);assert.equal(result.n,JSON.parse(evidence.feeds.pnl.message.text).n);assert.throws(()=>coherentSweep({...feeds,state:[]}));const changed=structuredClone(feeds);changed.price[0].frame.file='a'.repeat(64);assert.throws(()=>coherentSweep(changed));const later=structuredClone(feeds);later.pnl.push({...later.pnl[0],frame:{...later.pnl[0].frame,n:result.n+1}});assert.equal(coherentSweep(later).n,result.n)});
test('PnL comes from referee decimals; returns use starting balance; ordering validated',()=>{const frame=JSON.parse(evidence.feeds.pnl.message.text);const rows=standings(frame,'10000');assert.equal(rows.length,frame.top.length);assert.equal(rows[0].pnlDecimal,frame.top[0][1]);assert.equal(rows[0].returnPercent,rows[0].pnl/100);assert.throws(()=>standings({top:[[frame.top[0][0],'NaN']]},'10000'));assert.throws(()=>standings({top:[frame.top[0],frame.top[0]]},'10000'))});
test('retained posts keep a key after it leaves the latest board',()=>{const [a,b]=JSON.parse(evidence.feeds.pnl.message.text).top.map(entry=>entry[0]);const posts=[{ts:'2026-09-26T00:00:00.000Z',frame:{t:'pnl',n:1,mark:'220.00',top:[[a,'10.00'],[b,'9.00']]}},{ts:'2026-09-26T00:05:00.000Z',frame:{t:'pnl',n:2,mark:'221.00',top:[[a,'12.00']]}},{ts:'2026-09-26T00:04:00.000Z',frame:{t:'pnl',n:2,mark:'219.00',top:[[a,'1.00']]}}];const {sweeps,byDid}=indexPublished(posts,'10000');assert.equal(sweeps,2);assert.equal(byDid.get(b).at(-1).sweep,1);assert.equal(byDid.get(b).at(-1).pnlDecimal,'9.00');assert.equal(byDid.get(a).at(-1).pnlDecimal,'12.00');assert.equal(byDid.get(a).length,2)});
test('a signed entry predicts mark-to-market PnL after the 1% fee',()=>{const buy={id:'a',maker:'did:maker',taker:'did:taker',side:'buy',qty:200n,px:10000n,ts:'2026-09-26T00:00:00Z',seq:1,room:'close1'};const rows=predictEntries([buy,{...buy,id:'a',ts:'2026-09-26T00:01:00Z',px:11000n}],'110.00','0.01','10000');const maker=rows.find(row=>row.did==='did:maker'),taker=rows.find(row=>row.did==='did:taker');assert.equal(maker.pnlDecimal,'18.00');assert.equal(maker.positionSide,'long');assert.equal(maker.qty,'2.00');assert.equal(maker.entry,'100.00');assert.equal(maker.tradeCount,1);assert.equal(taker.pnlDecimal,'-22.00');assert.equal(taker.positionSide,'short');assert.equal(signedTrade({t:'trade',season:'close-1',terms:{id:'nope',maker:aDid(),px:'1.00',qty:'1.00',side:'buy',taker:'any',until:1},taker:aDid(),maker_sig:'x',taker_sig:'y'}),null)});
function aDid(){return 'did:key:z6MkgTDg3hEz4pwiFcJCDjRvR3hZbVWwy23oGuqFbFxu7Hne'}
