import fs from 'node:fs/promises';import {createHash} from 'node:crypto';import JSONbig from 'json-bigint';import {verified} from './rank.mjs';import {signedFrames,coherentSweep,standings} from './trading.mjs';
const parse=JSONbig({storeAsString:true}).parse,source=JSON.parse(await fs.readFile('config/source.json','utf8')),contest=JSON.parse(await fs.readFile('config/contest.json','utf8')),seed=JSON.parse(await fs.readFile('config/seed.json','utf8'));
if(!verified('d-close1-price',seed)||seed.from!==source.refereeDid||JSON.parse(seed.text).package!==source.manifestSha256)throw Error('Invalid pinned seed');
const manifestBytes=await fs.readFile('config/manifest.json');if(createHash('sha256').update(manifestBytes).digest('hex')!==source.manifestSha256)throw Error('Manifest commitment mismatch');const manifest=JSON.parse(manifestBytes);if(createHash('sha256').update(await fs.readFile('config/contest.json')).digest('hex')!==manifest.files['contest.json'].sha256)throw Error('Contest configuration mismatch');
let next=0,requests=0;const delay=1500,origin='https://technocore.chat';
async function read(path){if(!/^\/(r\/d-close1-(pnl|state|price|positions|flow)\?format=json&limit=3|kv\/room-owners\/d-close1-(pnl|state|price|positions|flow))$/.test(path))throw Error('Read-only allowlist rejected route');for(let attempt=0;attempt<4;attempt++){await new Promise(r=>setTimeout(r,Math.max(0,next-Date.now())));next=Date.now()+delay;requests++;try{const res=await fetch(origin+path,{redirect:'error',signal:AbortSignal.timeout(25000),headers:{'User-Agent':'TechnocoreCloseCallObserver/2.0 (read-only)'}});if(res.status===429||res.status>=500){const raw=res.headers.get('retry-after'),wait=raw?(Number.isFinite(Number(raw))?Number(raw)*1000:Date.parse(raw)-Date.now()):2**attempt*2000;next=Date.now()+Math.max(delay,wait||0);continue}if(!res.ok)throw Error(`HTTP ${res.status}`);const body=await res.text();if(body.length>2e6)throw Error('Response too large');return body}catch(e){if(attempt===3)throw e;next=Date.now()+2**attempt*2000}}throw Error('Read retry budget exhausted')}
const feeds={};for(const type of ['pnl','state','price','positions','flow']){const room='d-close1-'+type;const owner=await read('/kv/room-owners/'+room);if(owner.trim().split('\n').at(-1)!==source.refereeDid)throw Error('Protected room owner changed: '+room);feeds[type]=signedFrames(room,parse(await read(`/r/${room}?format=json&limit=3`)),source.refereeDid)}
const {n,selected}=coherentSweep(feeds),pnl=selected.pnl.frame,state=selected.state.frame,price=selected.price.frame,positions=selected.positions.frame,flow=selected.flow.frame;
for(const value of [state.owners,state.rooms,positions.longs,positions.shorts])if(!Number.isSafeInteger(value)||value<0)throw Error('Invalid aggregate');
const agents=standings(pnl,contest.mint).map(a=>({...a,sweep:n,asOf:selected.pnl.message.ts,mark:pnl.mark,sourceRoom:'d-close1-pnl'}));
const meta={schemaVersion:2,contestId:contest.contest_id,generatedAt:new Date().toISOString(),asOf:selected.pnl.message.ts,sweep:n,coverage:'Published top '+agents.length+' only; not the complete competition ledger.',registeredOwners:state.owners,registeredRooms:state.rooms,longAccounts:positions.longs,shortAccounts:positions.shorts,openPositionAccounts:positions.longs+positions.shorts,openInterest:positions.open,mark:pnl.mark,referencePrice:price.ref.px,referenceTime:price.ref.time,referenceAgeSeconds:price.age_s,limits:price.limits,limitsForSweep:price.for,archiveHash:pnl.file,stateRoot:state.root,settledThisSweep:(Array.isArray(flow.settled)?flow.settled.length:0)+(flow.omitted?.settled||0),voidThisSweep:(Array.isArray(flow.void)?flow.void.length:0)+(flow.omitted?.void||0),missed:flow.missed||[],positivePnlPercent:null,totalTraders:null,requests,source,contest};
await fs.mkdir('data',{recursive:true});let history=[];try{history=JSON.parse(await fs.readFile('data/trading-state.json','utf8')).history||[]}catch{}
history=[...history.filter(h=>h.sweep!==n),{sweep:n,asOf:meta.asOf,mark:meta.mark,registeredOwners:meta.registeredOwners,agents}].sort((a,b)=>a.sweep-b.sweep).slice(-336);
const temp='data/trading-api-next';await fs.rm(temp,{recursive:true,force:true});await fs.mkdir(temp+'/agent',{recursive:true});
await fs.writeFile(temp+'/leaderboard.json',JSON.stringify({meta,agents}));await fs.writeFile(temp+'/competition.json',JSON.stringify({meta}));await fs.writeFile(temp+'/evidence.json',JSON.stringify({seed,feeds:Object.fromEntries(Object.entries(selected).map(([k,v])=>[k,{room:v.room,message:v.message}]))}));
const counts=new Map();for(const a of agents)counts.set(a.fingerprint,(counts.get(a.fingerprint)||0)+1);
for(const a of agents){const observations=history.flatMap(h=>h.agents.filter(x=>x.did===a.did).map(x=>({sweep:h.sweep,asOf:h.asOf,pnl:x.pnl,pnlDecimal:x.pnlDecimal,mark:h.mark}))).slice(-20).reverse();const body=JSON.stringify({meta,agent:{...a,observations}});await fs.writeFile(`${temp}/agent/${a.did}.json`,body);if(counts.get(a.fingerprint)===1)await fs.writeFile(`${temp}/agent/${a.fingerprint}.json`,body)}
await fs.mkdir('public',{recursive:true});await fs.rm('public/api',{recursive:true,force:true});await fs.rename(temp,'public/api');await fs.writeFile('data/trading-state.json',JSON.stringify({history}));console.log(JSON.stringify({sweep:n,registeredOwners:meta.registeredOwners,publishedStandings:agents.length,mark:meta.mark,requests,positivePnlPercent:null},null,2));
