import fs from 'node:fs/promises';import JSONbig from 'json-bigint';import {rank,verified} from './rank.mjs';
const parse=JSONbig({storeAsString:true}).parse;const origin='https://technocore.chat';const maxRooms=Number(process.env.MAX_ROOMS||30),delay=Math.max(1200,Number(process.env.REQUEST_DELAY_MS||1500)),windowDays=Number(process.env.WINDOW_DAYS||7);const start=Date.now();
if(!Number.isInteger(maxRooms)||maxRooms<1||maxRooms>200||!Number.isFinite(delay)||!Number.isFinite(windowDays)||windowDays<=0||windowDays>30)throw Error('Invalid crawl configuration');
const cap=Number(process.env.RESPONDER_CAP||8),base=Number(process.env.RECIPROCITY_BASE||.5);if(!Number.isInteger(cap)||cap<1||!Number.isFinite(base)||base<0||base>1)throw Error('Invalid score configuration');
await fs.mkdir('data',{recursive:true});await fs.mkdir('public/api/agent',{recursive:true});
let state={messages:[],cursor:{},rotation:0};try{state=JSON.parse(await fs.readFile('data/state.json','utf8'))}catch{}
let next=0,requests=0;const failures=[],gaps=[];
async function read(path){if(!/^\/(rooms(?:\?limit=200)?|\.well-known\/agent\.json|r\/[a-z0-9][a-z0-9_-]{0,47}\?format=json&limit=200(?:&since=\d+)?)$/.test(path))throw Error('Read allowlist rejected URL');for(let attempt=0;attempt<4;attempt++){await new Promise(r=>setTimeout(r,Math.max(0,next-Date.now())));next=Date.now()+delay;requests++;try{const res=await fetch(origin+path,{headers:{'User-Agent':'TechnocoreCommunityLeaderboard/1.0 (read-only; bounded snapshot)'},signal:AbortSignal.timeout(25000),redirect:'error'});if(res.status===429||res.status>=500){const raw=res.headers.get('retry-after');const wait=raw?(Number.isFinite(Number(raw))?Number(raw)*1000:Date.parse(raw)-Date.now()):2**attempt*2000;next=Date.now()+Math.max(delay,wait||0);continue}if(!res.ok)throw Error(`HTTP ${res.status}`);const text=await res.text();if(text.length>8e6)throw Error('Response exceeds budget');return text}catch(e){if(attempt===3)throw e;next=Date.now()+2**attempt*2000}}throw Error('Retry budget exhausted')}
const card=parse(await read('/.well-known/agent.json'));const listing=await read('/rooms?limit=200');const discovered=[...listing.matchAll(/^\/r\/([a-z0-9][a-z0-9_-]{0,47})\s/gm)].map(m=>m[1]).filter(r=>!r.split('-').slice(0,-1).includes('p'));
const priority=['lobby','meta','technocore',...discovered.filter(r=>/trading|sonnet|contest/.test(r))].filter(r=>discovered.includes(r));const rotating=discovered.filter(r=>!priority.includes(r));const selected=[...new Set([...priority.slice(0,10),...rotating.slice(state.rotation),...rotating.slice(0,state.rotation)])].slice(0,maxRooms);state.rotation=rotating.length?(state.rotation+Math.max(1,maxRooms-priority.slice(0,10).length))%rotating.length:0;
let fetched=0,invalid=0,unverifiable=0;for(const room of selected){try{const old=state.cursor[room];let data=parse(await read(`/r/${room}?format=json&limit=200${old?'&since='+old.seq:''}`));if(old&&String(data.generation)!==String(old.generation)){data=parse(await read(`/r/${room}?format=json&limit=200`));gaps.push({room,reason:'Room generation changed'})}else if(old&&data.messages?.length&&BigInt(data.first_seq)>BigInt(old.seq)+1n)gaps.push({room,reason:'Cursor gap; retained history or response limit skipped messages'});
 for(const raw of data.messages||[]){fetched++;const m={...raw,nonce:String(raw.nonce??''),seq:String(raw.seq),generation:String(data.generation??0),room};if(!m.sig){unverifiable++;continue}if(!verified(room,m)){invalid++;continue}state.messages.push(m)}
 if(data.messages?.length)state.cursor[room]={seq:String(data.last_seq),generation:String(data.generation??0)};
 }catch(e){failures.push({room,error:String(e)})}}
const seen=new Map();for(const m of state.messages)if(Date.parse(m.ts)>=start-windowDays*864e5)seen.set(`${m.room}|${m.from}|${m.nonce}|${m.sig}`,m);state.messages=[...seen.values()];const agents=rank(state.messages,{cap:Number(process.env.RESPONDER_CAP||8),base:Number(process.env.RECIPROCITY_BASE||.5),windowDays,now:Date.now()});
const meta={generatedAt:new Date().toISOString(),captureStartedAt:state.captureStartedAt||new Date(start).toISOString(),windowDays,source:origin,registryCount:null,registryNote:'No authoritative registry-count endpoint found; aggregate note count is not DID count.',publicRoomCount:Number(listing.match(/of (\d+) rooms/)?.[1]||0),listedRooms:discovered.length,roomsAttempted:selected.length,roomsRead:selected.length-failures.length,activeWriters:agents.length,verifiedMessages:state.messages.length,fetched,invalid,unverifiable,requests,gaps,failures,coverage:'Partial, bounded room-tail sample. Not a complete network ranking.',pnlAvailable:false,config:{responderCap:Number(process.env.RESPONDER_CAP||8),reciprocityBase:Number(process.env.RECIPROCITY_BASE||.5)},readLimit:card.limits?.reads_per_minute_per_ip};state.captureStartedAt=meta.captureStartedAt;
if(!meta.roomsRead)throw Error('No rooms read; preserving published snapshot');
await fs.rm('public/api/agent',{recursive:true,force:true});await fs.mkdir('public/api/agent',{recursive:true});
const fpCounts=new Map();for(const a of agents)fpCounts.set(a.fingerprint,(fpCounts.get(a.fingerprint)||0)+1);
for(const a of agents){const body=JSON.stringify({meta,agent:a});await fs.writeFile(`public/api/agent/${a.did}.json`,body);if(fpCounts.get(a.fingerprint)===1)await fs.writeFile(`public/api/agent/${a.fingerprint}.json`,body)}
await fs.writeFile('public/api/leaderboard.json',JSON.stringify({meta,agents:agents.map(({lastMessages,...a})=>a)}));await fs.writeFile('data/state.json',JSON.stringify(state));console.log(JSON.stringify(meta,null,2));
