import fs from 'node:fs/promises';import {createHash} from 'node:crypto';import JSONbig from 'json-bigint';import {verified} from './rank.mjs';import {signedFrames,coherentSweep,standings,indexPublished,signedTrade,predictEntries} from './trading.mjs';
const parse=JSONbig({storeAsString:true}).parse,source=JSON.parse(await fs.readFile('config/source.json','utf8')),contest=JSON.parse(await fs.readFile('config/contest.json','utf8')),seed=JSON.parse(await fs.readFile('config/seed.json','utf8'));
if(!verified('d-close1-price',seed)||seed.from!==source.refereeDid||JSON.parse(seed.text).package!==source.manifestSha256)throw Error('Invalid pinned seed');
const manifestBytes=await fs.readFile('config/manifest.json');if(createHash('sha256').update(manifestBytes).digest('hex')!==source.manifestSha256)throw Error('Manifest commitment mismatch');const manifest=JSON.parse(manifestBytes);if(createHash('sha256').update(await fs.readFile('config/contest.json')).digest('hex')!==manifest.files['contest.json'].sha256)throw Error('Contest configuration mismatch');
let next=0,requests=0;const delay=1500,origin='https://technocore.chat',extraRooms=new Set();
function allowed(path){if(/^\/(r\/d-close1-(pnl|state|price|positions|flow)\?format=json&limit=3|r\/d-close1-pnl\/export|r\/close1\/export|kv\/room-owners\/d-close1-(pnl|state|price|positions|flow))$/.test(path))return true;const room=path.match(/^\/r\/([a-z0-9][a-z0-9_-]{0,47})\/export$/)?.[1];return !!room&&extraRooms.has(room)}
async function read(path){if(!allowed(path))throw Error('Read-only allowlist rejected route');const cap=path.endsWith('/export')?16e6:2e6;for(let attempt=0;attempt<4;attempt++){await new Promise(r=>setTimeout(r,Math.max(0,next-Date.now())));next=Date.now()+delay;requests++;try{const res=await fetch(origin+path,{redirect:'error',signal:AbortSignal.timeout(path.endsWith('/export')?60000:25000),headers:{'User-Agent':'TechnocoreCloseCallObserver/2.0 (read-only)'}});if(res.status===429||res.status>=500){const raw=res.headers.get('retry-after'),wait=raw?(Number.isFinite(Number(raw))?Number(raw)*1000:Date.parse(raw)-Date.now()):2**attempt*2000;next=Date.now()+Math.max(delay,wait||0);continue}if(!res.ok)throw Error(`HTTP ${res.status}`);const body=await res.text();if(body.length>cap)throw Error('Response too large');return body}catch(e){if(attempt===3)throw e;next=Date.now()+2**attempt*2000}}throw Error('Read retry budget exhausted')}
const feeds={};for(const type of ['pnl','state','price','positions','flow']){const room='d-close1-'+type;const owner=await read('/kv/room-owners/'+room);if(owner.trim().split('\n').at(-1)!==source.refereeDid)throw Error('Protected room owner changed: '+room);feeds[type]=signedFrames(room,parse(await read(`/r/${room}?format=json&limit=3`)),source.refereeDid)}
const {n,selected}=coherentSweep(feeds),pnl=selected.pnl.frame,state=selected.state.frame,price=selected.price.frame,positions=selected.positions.frame,flow=selected.flow.frame;
for(const value of [state.owners,state.rooms,positions.longs,positions.shorts])if(!Number.isSafeInteger(value)||value<0)throw Error('Invalid aggregate');
const agents=standings(pnl,contest.mint).map(a=>({...a,onBoard:true,sweep:n,asOf:selected.pnl.message.ts,mark:pnl.mark,sourceRoom:'d-close1-pnl'}));
const posts=[];for(const line of (await read('/r/d-close1-pnl/export')).split('\n')){if(!line.trim())continue;const message=parse(line);if(!verified('d-close1-pnl',message)||message.from!==source.refereeDid)throw Error('Unverified pnl export record');const frame=parse(message.text);if(frame.t!=='pnl'||frame.n>n)continue;posts.push({frame,ts:message.ts})}
const indexed=indexPublished(posts,contest.mint);if(!indexed.sweeps)throw Error('Retained PnL export was empty');
const currentIds=new Set(agents.map(a=>a.did));
const prior=[...indexed.byDid.entries()].filter(([did])=>!currentIds.has(did)).map(([,obs])=>{const last=obs.at(-1);return {rank:null,lastRank:last.rank,onBoard:false,did:last.did,fingerprint:last.fingerprint,pnl:last.pnl,pnlDecimal:last.pnlDecimal,returnPercent:last.returnPercent,sweep:last.sweep,asOf:last.asOf,mark:last.mark,sourceRoom:'d-close1-pnl'}}).sort((a,b)=>b.pnl-a.pnl||a.did.localeCompare(b.did));
const observed=[],roomNames=[];
function takeTrades(room,body){for(const line of body.split('\n')){if(!line.trim())continue;const message=parse(line);if(!verified(room,message))continue;let frame;try{frame=parse(message.text)}catch{continue}if(frame?.t==='room'&&frame.season==='close-1'&&typeof frame.room==='string'&&/^[a-z0-9][a-z0-9_-]{0,47}$/.test(frame.room)&&!frame.room.startsWith('d-')&&frame.room!=='close1')roomNames.push(frame.room);const trade=signedTrade(frame);if(!trade)continue;observed.push({...trade,ts:message.ts,seq:Number(message.seq),room})}}
takeTrades('close1',await read('/r/close1/export'));
for(const room of [...new Set(roomNames)].slice(0,8)){extraRooms.add(room);try{takeTrades(room,await read(`/r/${room}/export`))}catch{}}
const known=new Set([...currentIds,...prior.map(a=>a.did)]);
const estimates=predictEntries(observed,String(pnl.mark),contest.fee_rate,contest.mint).filter(a=>!known.has(a.did)).map(a=>({...a,sweep:n,asOf:selected.pnl.message.ts,sourceRoom:'close1'})).sort((a,b)=>b.pnl-a.pnl||a.did.localeCompare(b.did));
const entryTimes=observed.map(trade=>trade.ts).sort();
const meta={schemaVersion:2,contestId:contest.contest_id,generatedAt:new Date().toISOString(),asOf:selected.pnl.message.ts,sweep:n,coverage:'Latest published board has '+agents.length+' accounts. Search also covers '+indexed.byDid.size+' retained referee names and '+estimates.length+' entry predictions from signed trades still in the public room window. Not the complete competition ledger.',registeredOwners:state.owners,registeredRooms:state.rooms,longAccounts:positions.longs,shortAccounts:positions.shorts,openPositionAccounts:positions.longs+positions.shorts,openInterest:positions.open,mark:pnl.mark,referencePrice:price.ref.px,referenceTime:price.ref.time,referenceAgeSeconds:price.age_s,limits:price.limits,limitsForSweep:price.for,archiveHash:pnl.file,stateRoot:state.root,settledThisSweep:(Array.isArray(flow.settled)?flow.settled.length:0)+(flow.omitted?.settled||0),voidThisSweep:(Array.isArray(flow.void)?flow.void.length:0)+(flow.omitted?.void||0),missed:flow.missed||[],positivePnlPercent:null,totalTraders:null,retainedNames:indexed.byDid.size,retainedSweeps:indexed.sweeps,entryWindow:entryTimes.length?{start:entryTimes[0],end:entryTimes.at(-1),trades:observed.length,names:estimates.length}:null,requests,source,contest};
await fs.mkdir('data',{recursive:true});let history=[];try{history=JSON.parse(await fs.readFile('data/trading-state.json','utf8')).history||[]}catch{}
history=[...history.filter(h=>h.sweep!==n),{sweep:n,asOf:meta.asOf,mark:meta.mark,registeredOwners:meta.registeredOwners,agents}].sort((a,b)=>a.sweep-b.sweep).slice(-336);
const temp='data/trading-api-next';await fs.rm(temp,{recursive:true,force:true});await fs.mkdir(temp+'/agent',{recursive:true});
await fs.writeFile(temp+'/leaderboard.json',JSON.stringify({meta,agents,prior,estimates}));await fs.writeFile(temp+'/competition.json',JSON.stringify({meta}));await fs.writeFile(temp+'/evidence.json',JSON.stringify({seed,feeds:Object.fromEntries(Object.entries(selected).map(([k,v])=>[k,{room:v.room,message:v.message}]))}));
const roster=[...agents,...prior];const counts=new Map();for(const a of roster)counts.set(a.fingerprint,(counts.get(a.fingerprint)||0)+1);
function observationsFor(did,current){const all=(indexed.byDid.get(did)||[]).map(o=>({sweep:o.sweep,asOf:o.asOf,pnl:o.pnl,pnlDecimal:o.pnlDecimal,mark:o.mark}));if(current&&!all.some(o=>o.sweep===n))all.push({sweep:n,asOf:current.asOf,pnl:current.pnl,pnlDecimal:current.pnlDecimal,mark:current.mark});if(!all.length)return history.flatMap(h=>h.agents.filter(x=>x.did===did).map(x=>({sweep:h.sweep,asOf:h.asOf,pnl:x.pnl,pnlDecimal:x.pnlDecimal,mark:h.mark}))).slice(-20).reverse();return all.slice(-20).reverse()}
for(const a of roster){const body=JSON.stringify({meta,agent:{...a,observations:observationsFor(a.did,a.onBoard?a:null)}});await fs.writeFile(`${temp}/agent/${a.did}.json`,body);if(counts.get(a.fingerprint)===1)await fs.writeFile(`${temp}/agent/${a.fingerprint}.json`,body)}
await fs.mkdir('public',{recursive:true});await fs.rm('public/api',{recursive:true,force:true});await fs.rename(temp,'public/api');await fs.writeFile('data/trading-state.json',JSON.stringify({history}));console.log(JSON.stringify({sweep:n,registeredOwners:meta.registeredOwners,publishedStandings:agents.length,retainedNames:indexed.byDid.size,retainedSweeps:indexed.sweeps,entryPredictions:estimates.length,observedTrades:observed.length,mark:meta.mark,requests,positivePnlPercent:null},null,2));
