import {verified,verifyText,fingerprint} from './rank.mjs';
export function signedFrames(room,envelope,did){return (envelope.messages||[]).filter(m=>m.from===did&&verified(room,m)).flatMap(m=>{try{return [{message:m,frame:JSON.parse(m.text),room}]}catch{return []}})}
export function coherentSweep(feeds){const types=['pnl','state','price','positions','flow'];const sets=types.map(t=>feeds[t].filter(x=>x.frame.t===t&&Number.isSafeInteger(x.frame.n)));const common=sets[0].map(x=>x.frame.n).filter(n=>sets.every(s=>s.some(x=>x.frame.n===n))).sort((a,b)=>b-a);if(!common.length)throw Error('No common signed sweep across referee feeds');const n=common[0],selected=Object.fromEntries(types.map((t,i)=>[t,sets[i].find(x=>x.frame.n===n)]));const hashes=new Set(Object.values(selected).map(x=>x.frame.file));if(hashes.size!==1||!Array.from(hashes).every(h=>/^[a-f0-9]{64}$/.test(h)))throw Error('Inconsistent archive commitment');return {n,selected};}
export function standings(frame,mint){if(!Array.isArray(frame.top))throw Error('No published standings');const seen=new Set();let last=Infinity;return frame.top.map((entry,index)=>{if(!Array.isArray(entry)||entry.length!==2||!/^did:key:z6Mk[1-9A-HJ-NP-Za-km-z]{44}$/.test(entry[0])||!/^[-+]?\d+(?:\.\d+)?$/.test(String(entry[1])))throw Error('Invalid standing');const [did,decimal]=entry,pnl=Number(decimal);if(!Number.isFinite(pnl)||seen.has(did)||pnl>last)throw Error('Invalid standings order');seen.add(did);last=pnl;return {rank:index+1,did,fingerprint:fingerprint(did),pnl,pnlDecimal:String(decimal),returnPercent:pnl/Number(mint)*100};});}
export function indexPublished(posts,mint){const bySweep=new Map();for(const post of posts){const frame=post?.frame;if(!frame||frame.t!=='pnl'||!Number.isSafeInteger(frame.n)||typeof post.ts!=='string')throw Error('Invalid retained PnL post');const prev=bySweep.get(frame.n);if(!prev||post.ts>prev.ts)bySweep.set(frame.n,post)}const byDid=new Map();for(const n of [...bySweep.keys()].sort((a,b)=>a-b)){const post=bySweep.get(n);for(const row of standings(post.frame,mint)){const list=byDid.get(row.did)||[];list.push({sweep:n,asOf:post.ts,pnl:row.pnl,pnlDecimal:row.pnlDecimal,mark:String(post.frame.mark),rank:row.rank,did:row.did,fingerprint:row.fingerprint,returnPercent:row.returnPercent});byDid.set(row.did,list)}}return {sweeps:bySweep.size,byDid};}
const didKey=/^did:key:z6Mk[1-9A-HJ-NP-Za-km-z]{44}$/,tradeId=/^[A-Za-z0-9_-]{1,64}$/,centsText=/^[0-9]{1,7}(?:\.[0-9]{1,2})?$/;
function cents(text){if(typeof text!=='string'||!centsText.test(text))return null;const [whole,frac='']=text.split('.');const value=BigInt(whole)*100n+BigInt((frac+'00').slice(0,2));return value>0n?value:null}
function formatMicro(micro){const neg=micro<0n,abs=neg?-micro:micro,whole=abs/1000000n,frac=(abs%1000000n).toString().padStart(6,'0').replace(/0+$/,'');const body=frac.length>=2?`${whole}.${frac}`:`${whole}.${frac.padEnd(2,'0')}`;return `${neg?'-':''}${body}`}
export function signedTrade(body){const terms=body?.terms;if(body?.t!=='trade'||body.season!=='close-1'||!terms)return null;const order=['id','maker','px','qty','side','taker','until'];if(order.some(key=>!(key in terms)))return null;const canon=JSON.stringify(Object.fromEntries(order.map(key=>[key,terms[key]])));const qty=cents(terms.qty),px=cents(terms.px),taker=body.taker;if(!tradeId.test(terms.id)||!didKey.test(terms.maker)||(terms.side!=='buy'&&terms.side!=='sell')||qty===null||px===null||!Number.isInteger(terms.until)||!didKey.test(taker))return null;if(terms.taker!=='any'&&terms.taker!==taker)return null;if(!verifyText(terms.maker,`close-1|terms|${canon}`,body.maker_sig)||!verifyText(taker,`close-1|accept|${canon}|${taker}`,body.taker_sig))return null;return {id:terms.id,maker:terms.maker,taker,side:terms.side,qty,px,until:terms.until}}
function applyLot(account,side,qty,px,fee){account.cash-=fee;let left=qty;while(left>0n&&account.lots.length&&account.lots[0].qty*BigInt(side)<0n){const lot=account.lots[0],size=left<absBig(lot.qty)?left:absBig(lot.qty);account.cash+=side<0?size*px*100n:size*(2n*lot.px-px)*100n;left-=size;if(size===absBig(lot.qty))account.lots.shift();else lot.qty+=BigInt(side)*size}if(left>0n){account.cash-=left*px*100n;account.lots.push({qty:BigInt(side)*left,px})}}
function absBig(value){return value<0n?-value:value}
function equity(account,mark){let value=account.cash;for(const lot of account.lots)value+=lot.qty>0n?lot.qty*mark*100n:(-lot.qty)*(2n*lot.px-mark)*100n;return value}
export function predictEntries(trades,markText,feeRate,mint){if(feeRate!=='0.01')throw Error('Entry prediction expects the 1% fee');const mark=cents(markText);if(mark===null)throw Error('Invalid mark');const seen=new Map();for(const trade of trades){const prev=seen.get(trade.id);if(!prev||trade.ts<prev.ts||(trade.ts===prev.ts&&trade.seq<prev.seq))seen.set(trade.id,trade)}const ordered=[...seen.values()].sort((a,b)=>a.ts<b.ts?-1:a.ts>b.ts?1:a.room.localeCompare(b.room)||a.seq-b.seq);const books=new Map();for(const trade of ordered){const maker=books.get(trade.maker)||{cash:0n,lots:[],trades:0},taker=trade.maker===trade.taker?maker:(books.get(trade.taker)||{cash:0n,lots:[],trades:0});const side=trade.side==='buy'?1:-1,fee=trade.qty*trade.px;if(maker===taker){maker.cash-=fee*2n;maker.trades+=1}else{applyLot(maker,side,trade.qty,trade.px,fee);applyLot(taker,-side,trade.qty,trade.px,fee);maker.trades+=1;taker.trades+=1;books.set(trade.taker,taker)}books.set(trade.maker,maker)}return [...books.entries()].map(([did,book])=>{const micro=equity(book,mark),pnlDecimal=formatMicro(micro),pnl=Number(pnlDecimal),net=book.lots.reduce((sum,lot)=>sum+lot.qty,0n);const prices=new Set(book.lots.map(lot=>lot.px));return {estimated:true,onBoard:false,rank:null,did,fingerprint:fingerprint(did),pnl,pnlDecimal,returnPercent:pnl/Number(mint)*100,qty:formatMicro(net*10000n),entry:prices.size===1?formatMicro([...prices][0]*10000n):null,positionSide:net>0n?'long':net<0n?'short':'flat',tradeCount:book.trades,mark:markText}})}
